### ISSUE TITLE
no 'exceptions' member

### ISSUE THREAD

**Issue by abhiroopdutta** [fallenshell/coverpy#10]
Hey, I was trying out your library and I get this error - 
Instance of 'CoverPy' has no 'exceptions' member

Could you help me with this ?

**Comment by matteing** [comment]
hm. it's been a while since I last worked on this.

It's actually written wrong in the docs! Just import from coverpy import NoResultsException, coverpy

**Comment by abhiroopdutta** [comment]
Yeah I figured it out, thanks anyway! Your library really helped my project.
